//
//  StabilityAIEditSearchAndReplaceRequestBody.swift
//  AIProxy
//
//  Created by Vladimir Lyukov on 04.04.2025.
//

import Foundation

// The models below are derived from this reference:
// https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1search-and-replace/post
public struct StabilityAIEditSearchAndReplaceRequestBody: MultipartFormEncodable {

    // MARK: Required

    /// The image you wish to edit.
    /// - Supported Formats:
    ///   jpeg
    ///   png
    ///   webp
    /// - Validation Rules:
    ///   Every side must be at least 64 pixels
    ///   Total pixel count must be between 4,096 and 9,437,184 pixels
    ///   The aspect ratio must be between 1:2.5 and 2.5:1
    public let image: Data

    /// What you wish to see in the output image. A strong, descriptive prompt
    /// that clearly defines elements, colors, and subjects will lead to better results.
    public let prompt: String

    /// Short description of what to inpaint in the `image`.
    public let searchPrompt: String

    // MARK: Optional

    /// A blurb of text describing what you do not wish to see in the output image.
    /// This is an advanced feature.
    public let negativePrompt: String?

    /// Grows the edges of the mask outward in all directions by the specified
    /// number of pixels. The expanded area around the mask will be blurred,
    /// which can help smooth the transition between inpainted content and the
    /// original image.
    /// Try this parameter if you notice seams or rough edges around the
    /// inpainted content.
    /// Possible values: `[ 0 .. 20 ]`
    /// Default value: `3`
    public let growMask: Int?

    /// A specific value that is used to guide the 'randomness' of the generation. (Omit this
    /// parameter or pass `0` to use a random seed.)
    /// Possible values: `[ 0 .. 4294967294 ]`
    public let seed: Int?

    /// Dictates the `content-type` of the generated image
    /// Defaults to `png`
    public let outputFormat: StabilityAIUltraOutputFormat?

    /// Guides the image model towards a particular style.
    public let stylePreset: StabilityAIStylePreset?

    public var formFields: [FormField] {
        let theFields: [FormField] = [
            .fileField(name: "image", content: image, contentType: "image/jpeg", filename: "aiproxy.jpg"),
            .textField(name: "prompt", content: self.prompt),
            .textField(name: "search_prompt", content: self.searchPrompt),
            self.negativePrompt.flatMap { .textField(name: "negative_prompt", content: $0) },
            self.growMask.flatMap { .textField(name: "grow_mask", content: String($0)) },
            self.seed.flatMap { .textField(name: "seed", content: String($0)) },
            self.outputFormat.flatMap { .textField(name: "output_format", content: $0.rawValue) },
            self.stylePreset.flatMap { .textField(name: "style_preset", content: $0.rawValue) },
        ].compactMap { $0 }

        return theFields
    }

    // This memberwise initializer is autogenerated.
    // To regenerate, use `cmd-shift-a` > Generate Memberwise Initializer
    // To format, place the cursor in the initializer's parameter list and use `ctrl-m`
    public init(
        image: Data,
        prompt: String,
        searchPrompt: String,
        negativePrompt: String? = nil,
        growMask: Int? = nil,
        seed: Int? = nil,
        outputFormat: StabilityAIUltraOutputFormat? = nil,
        stylePreset: StabilityAIStylePreset? = nil
    ) {
        self.image = image
        self.prompt = prompt
        self.searchPrompt = searchPrompt
        self.negativePrompt = negativePrompt
        self.growMask = growMask
        self.seed = seed
        self.outputFormat = outputFormat
        self.stylePreset = stylePreset
    }
}
