//
//  StabilityAIEditEraseRequestBody.swift
//  AIProxy
//
//  Created by Vladimir Lyukov on 04.04.2025.
//

import Foundation

// The models below are derived from this reference:
// https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1inpaint/post
public struct StabilityAIEditEraseRequestBody: MultipartFormEncodable {

    // MARK: Required

    /// The image you wish to inpaint.
    /// - Supported Formats:
    ///   jpeg
    ///   png
    ///   webp
    /// - Validation Rules:
    ///   Every side must be at least 64 pixels
    ///   Total pixel count must be between 4,096 and 9,437,184 pixels
    public let image: Data

    /// Controls the strength of the inpainting process on a per-pixel basis,
    /// either via a second image (passed into this parameter) or via the alpha
    /// channel of the `image` parameter.
    /// **Passing in a Mask**
    /// The image passed to this parameter should be a black and white image
    /// that represents, at any pixel, the strength of inpainting based on how
    /// dark or light the given pixel is. Completely black pixels represent no
    /// inpainting strength while completely white pixels represent maximum
    /// strength.
    /// In the event the mask is a different size than the `image` parameter,
    /// it will be automatically resized.
    /// **Alpha Channel Support**
    /// If you don't provide an explicit mask, one will be derived from the
    /// alpha channel of the `image` parameter. Transparent pixels will be
    /// inpainted while opaque pixels will be preserved.
    /// In the event an `image` with an alpha channel is provided along with a
    /// `mask`, the mask will take precedence.
    public let mask: Data?

    /// Grows the edges of the mask outward in all directions by the specified
    /// number of pixels. The expanded area around the mask will be blurred,
    /// which can help smooth the transition between inpainted content and the
    /// original image.
    /// Try this parameter if you notice seams or rough edges around the
    /// inpainted content.
    /// Note: Excessive growth may obscure fine details in the mask and/or
    /// merge nearby masked regions.
    /// Possible values: `[ 0 .. 100 ]`
    /// Default value: `5`
    public let growMask: Int?

    /// A specific value that is used to guide the 'randomness' of the generation. (Omit this
    /// parameter or pass `0` to use a random seed.)
    /// Possible values: `[ 0 .. 4294967294 ]`
    public let seed: Int?

    /// Dictates the `content-type` of the generated image
    /// Defaults to `png`
    public let outputFormat: StabilityAIUltraOutputFormat?

    public var formFields: [FormField] {
        let theFields: [FormField] = [
            .fileField(name: "image", content: image, contentType: "image/jpeg", filename: "aiproxy.jpg"),
            self.mask.flatMap { .fileField(name: "mask", content: $0, contentType: "image/jpeg", filename: "mask.jpg") },
            self.growMask.flatMap { .textField(name: "grow_mask", content: String($0)) },
            self.seed.flatMap { .textField(name: "seed", content: String($0)) },
            self.outputFormat.flatMap { .textField(name: "output_format", content: $0.rawValue) },
        ].compactMap { $0 }

        return theFields

    }

    // This memberwise initializer is autogenerated.
    // To regenerate, use `cmd-shift-a` > Generate Memberwise Initializer
    // To format, place the cursor in the initializer's parameter list and use `ctrl-m`
    public init(
        image: Data,
        mask: Data? = nil,
        growMask: Int? = nil,
        seed: Int? = nil,
        outputFormat: StabilityAIUltraOutputFormat? = nil,
    ) {
        self.image = image
        self.mask = mask
        self.growMask = growMask
        self.seed = seed
        self.outputFormat = outputFormat
    }
}

